//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectInfo", Namespace="http://labs.shahed.net/")]
    [System.SerializableAttribute()]
    public partial class ProjectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Framework.DataService.ArrayOfString GestureNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Framework.DataService.ArrayOfString GestureNames {
            get {
                return this.GestureNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GestureNamesField, value) != true)) {
                    this.GestureNamesField = value;
                    this.RaisePropertyChanged("GestureNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://labs.shahed.net/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://labs.shahed.net/", ConfigurationName="DataService.GestureServiceSoap")]
    public interface GestureServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/ConnectivityCheck", ReplyAction="*")]
        bool ConnectivityCheck();
        
        // CODEGEN: Generating message contract since element name userName from namespace http://labs.shahed.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/AddGestureData", ReplyAction="*")]
        Framework.DataService.AddGestureDataResponse AddGestureData(Framework.DataService.AddGestureDataRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://labs.shahed.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/GetProjectsByUser", ReplyAction="*")]
        Framework.DataService.GetProjectsByUserResponse GetProjectsByUser(Framework.DataService.GetProjectsByUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://labs.shahed.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/GetGestureData", ReplyAction="*")]
        Framework.DataService.GetGestureDataResponse GetGestureData(Framework.DataService.GetGestureDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/Delete", ReplyAction="*")]
        void Delete(int id);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://labs.shahed.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/IsUserNameUnique", ReplyAction="*")]
        Framework.DataService.IsUserNameUniqueResponse IsUserNameUnique(Framework.DataService.IsUserNameUniqueRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://labs.shahed.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://labs.shahed.net/LastUpdatedAt", ReplyAction="*")]
        Framework.DataService.LastUpdatedAtResponse LastUpdatedAt(Framework.DataService.LastUpdatedAtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGestureDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGestureData", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.AddGestureDataRequestBody Body;
        
        public AddGestureDataRequest() {
        }
        
        public AddGestureDataRequest(Framework.DataService.AddGestureDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class AddGestureDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gestureName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gestureData;
        
        public AddGestureDataRequestBody() {
        }
        
        public AddGestureDataRequestBody(string userName, string projectName, string gestureName, string gestureData) {
            this.userName = userName;
            this.projectName = projectName;
            this.gestureName = gestureName;
            this.gestureData = gestureData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGestureDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGestureDataResponse", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.AddGestureDataResponseBody Body;
        
        public AddGestureDataResponse() {
        }
        
        public AddGestureDataResponse(Framework.DataService.AddGestureDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddGestureDataResponseBody {
        
        public AddGestureDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectsByUser", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.GetProjectsByUserRequestBody Body;
        
        public GetProjectsByUserRequest() {
        }
        
        public GetProjectsByUserRequest(Framework.DataService.GetProjectsByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class GetProjectsByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetProjectsByUserRequestBody() {
        }
        
        public GetProjectsByUserRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectsByUserResponse", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.GetProjectsByUserResponseBody Body;
        
        public GetProjectsByUserResponse() {
        }
        
        public GetProjectsByUserResponse(Framework.DataService.GetProjectsByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class GetProjectsByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Framework.DataService.ProjectInfo[] GetProjectsByUserResult;
        
        public GetProjectsByUserResponseBody() {
        }
        
        public GetProjectsByUserResponseBody(Framework.DataService.ProjectInfo[] GetProjectsByUserResult) {
            this.GetProjectsByUserResult = GetProjectsByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGestureDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGestureData", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.GetGestureDataRequestBody Body;
        
        public GetGestureDataRequest() {
        }
        
        public GetGestureDataRequest(Framework.DataService.GetGestureDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class GetGestureDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gestureName;
        
        public GetGestureDataRequestBody() {
        }
        
        public GetGestureDataRequestBody(string userName, string projectName, string gestureName) {
            this.userName = userName;
            this.projectName = projectName;
            this.gestureName = gestureName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGestureDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGestureDataResponse", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.GetGestureDataResponseBody Body;
        
        public GetGestureDataResponse() {
        }
        
        public GetGestureDataResponse(Framework.DataService.GetGestureDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class GetGestureDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGestureDataResult;
        
        public GetGestureDataResponseBody() {
        }
        
        public GetGestureDataResponseBody(string GetGestureDataResult) {
            this.GetGestureDataResult = GetGestureDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserNameUniqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserNameUnique", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.IsUserNameUniqueRequestBody Body;
        
        public IsUserNameUniqueRequest() {
        }
        
        public IsUserNameUniqueRequest(Framework.DataService.IsUserNameUniqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class IsUserNameUniqueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public IsUserNameUniqueRequestBody() {
        }
        
        public IsUserNameUniqueRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserNameUniqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserNameUniqueResponse", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.IsUserNameUniqueResponseBody Body;
        
        public IsUserNameUniqueResponse() {
        }
        
        public IsUserNameUniqueResponse(Framework.DataService.IsUserNameUniqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class IsUserNameUniqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserNameUniqueResult;
        
        public IsUserNameUniqueResponseBody() {
        }
        
        public IsUserNameUniqueResponseBody(bool IsUserNameUniqueResult) {
            this.IsUserNameUniqueResult = IsUserNameUniqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LastUpdatedAtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastUpdatedAt", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.LastUpdatedAtRequestBody Body;
        
        public LastUpdatedAtRequest() {
        }
        
        public LastUpdatedAtRequest(Framework.DataService.LastUpdatedAtRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class LastUpdatedAtRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public LastUpdatedAtRequestBody() {
        }
        
        public LastUpdatedAtRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LastUpdatedAtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastUpdatedAtResponse", Namespace="http://labs.shahed.net/", Order=0)]
        public Framework.DataService.LastUpdatedAtResponseBody Body;
        
        public LastUpdatedAtResponse() {
        }
        
        public LastUpdatedAtResponse(Framework.DataService.LastUpdatedAtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://labs.shahed.net/")]
    public partial class LastUpdatedAtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime LastUpdatedAtResult;
        
        public LastUpdatedAtResponseBody() {
        }
        
        public LastUpdatedAtResponseBody(System.DateTime LastUpdatedAtResult) {
            this.LastUpdatedAtResult = LastUpdatedAtResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestureServiceSoapChannel : Framework.DataService.GestureServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestureServiceSoapClient : System.ServiceModel.ClientBase<Framework.DataService.GestureServiceSoap>, Framework.DataService.GestureServiceSoap {
        
        public GestureServiceSoapClient() {
        }
        
        public GestureServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestureServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestureServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestureServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ConnectivityCheck() {
            return base.Channel.ConnectivityCheck();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.DataService.AddGestureDataResponse Framework.DataService.GestureServiceSoap.AddGestureData(Framework.DataService.AddGestureDataRequest request) {
            return base.Channel.AddGestureData(request);
        }
        
        public void AddGestureData(string userName, string projectName, string gestureName, string gestureData) {
            Framework.DataService.AddGestureDataRequest inValue = new Framework.DataService.AddGestureDataRequest();
            inValue.Body = new Framework.DataService.AddGestureDataRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.projectName = projectName;
            inValue.Body.gestureName = gestureName;
            inValue.Body.gestureData = gestureData;
            Framework.DataService.AddGestureDataResponse retVal = ((Framework.DataService.GestureServiceSoap)(this)).AddGestureData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.DataService.GetProjectsByUserResponse Framework.DataService.GestureServiceSoap.GetProjectsByUser(Framework.DataService.GetProjectsByUserRequest request) {
            return base.Channel.GetProjectsByUser(request);
        }
        
        public Framework.DataService.ProjectInfo[] GetProjectsByUser(string userName) {
            Framework.DataService.GetProjectsByUserRequest inValue = new Framework.DataService.GetProjectsByUserRequest();
            inValue.Body = new Framework.DataService.GetProjectsByUserRequestBody();
            inValue.Body.userName = userName;
            Framework.DataService.GetProjectsByUserResponse retVal = ((Framework.DataService.GestureServiceSoap)(this)).GetProjectsByUser(inValue);
            return retVal.Body.GetProjectsByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.DataService.GetGestureDataResponse Framework.DataService.GestureServiceSoap.GetGestureData(Framework.DataService.GetGestureDataRequest request) {
            return base.Channel.GetGestureData(request);
        }
        
        public string GetGestureData(string userName, string projectName, string gestureName) {
            Framework.DataService.GetGestureDataRequest inValue = new Framework.DataService.GetGestureDataRequest();
            inValue.Body = new Framework.DataService.GetGestureDataRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.projectName = projectName;
            inValue.Body.gestureName = gestureName;
            Framework.DataService.GetGestureDataResponse retVal = ((Framework.DataService.GestureServiceSoap)(this)).GetGestureData(inValue);
            return retVal.Body.GetGestureDataResult;
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.DataService.IsUserNameUniqueResponse Framework.DataService.GestureServiceSoap.IsUserNameUnique(Framework.DataService.IsUserNameUniqueRequest request) {
            return base.Channel.IsUserNameUnique(request);
        }
        
        public bool IsUserNameUnique(string userName) {
            Framework.DataService.IsUserNameUniqueRequest inValue = new Framework.DataService.IsUserNameUniqueRequest();
            inValue.Body = new Framework.DataService.IsUserNameUniqueRequestBody();
            inValue.Body.userName = userName;
            Framework.DataService.IsUserNameUniqueResponse retVal = ((Framework.DataService.GestureServiceSoap)(this)).IsUserNameUnique(inValue);
            return retVal.Body.IsUserNameUniqueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.DataService.LastUpdatedAtResponse Framework.DataService.GestureServiceSoap.LastUpdatedAt(Framework.DataService.LastUpdatedAtRequest request) {
            return base.Channel.LastUpdatedAt(request);
        }
        
        public System.DateTime LastUpdatedAt(string userName) {
            Framework.DataService.LastUpdatedAtRequest inValue = new Framework.DataService.LastUpdatedAtRequest();
            inValue.Body = new Framework.DataService.LastUpdatedAtRequestBody();
            inValue.Body.userName = userName;
            Framework.DataService.LastUpdatedAtResponse retVal = ((Framework.DataService.GestureServiceSoap)(this)).LastUpdatedAt(inValue);
            return retVal.Body.LastUpdatedAtResult;
        }
    }
}
