<?xml version="1.0" encoding="utf-8"?>
<Database Name="shahedk_gestures" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=shahed.me;Initial Catalog=shahedk_gestures;User ID=shahedk_gestures" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="shahedk_gesturesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="shahedk_gestures.Gesture" Member="Gestures">
    <Type Name="Gesture">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GestureName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="UserProject_Gesture" Member="UserProject" ThisKey="ProjectId" OtherKey="Id" Type="UserProject" IsForeignKey="true" />
      <Association Name="User_Gesture" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="shahedk_gestures.UserProject" Member="UserProjects">
    <Type Name="UserProject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserProject_Gesture" Member="Gestures" ThisKey="Id" OtherKey="ProjectId" Type="Gesture" />
      <Association Name="User_UserProject" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="shahedk_gestures.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Gesture" Member="Gestures" ThisKey="Id" OtherKey="UserId" Type="Gesture" />
      <Association Name="User_UserProject" Member="UserProjects" ThisKey="Id" OtherKey="UserId" Type="UserProject" />
      <Association Name="User_UserActivity" Member="UserActivities" ThisKey="Id" OtherKey="UserId" Type="UserActivity" />
    </Type>
  </Table>
  <Table Name="shahedk_gestures.UserActivity" Member="UserActivities">
    <Type Name="UserActivity" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserActivity" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="shahedk_gestures.GetLastActivityByUser" Method="GetLastActivityByUser">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>